server:
  port: 8088
spring:
  application:
    name: mybadis-demo-8080
  datasource: #??MySQL??????
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

#??mybatis??????
mybatis:
  type-aliases-package: com.shopping.entity
  mapper-locations: classpath*:mappers/*.xml
  #??mybatis?????????1:mapper-locations:??mybatisSQL????????
  #2:type-aliases-package:??mybatis????????

